### PR TITLE
feat: setup, teardown and throwable benchmark

### PR DESCRIPTION
**Pull request by ORyanHampton**
## Description

Some benchmarks require an environment be setup before running them. In order to help setup these environments in fresh states Setup and Teardown methods were added to help with this.
Throwing functions can be common place, so having a built in handler for these is very helpful in keeping benchmarks more easily readable and handle errors.

## How Has This Been Tested?

Ran in xcode with setup, teardown and throwing benchmarks.

## Minimal checklist:

- [x] I have performed a self-review of my own code 
- [ ] I have added `DocC` code-level documentation for any public interfaces exported by the package
- [ ] I have added unit and/or integration tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hassila** [comment]
Thanks, it makes sense to support throwable benchmarks.
With regard to setup/teardown, you can write generic setup code outside the scope of the Benchmark definitions, e.g:

```swift
@main
extension BenchmarkRunner {}

@_dynamicReplacement(for: registerBenchmarks)
func benchmarks() {
    Benchmark.defaultConfiguration = .init(warmupIterations: 0,
                                           maxDuration: .seconds(1),
                                           maxIterations: Int.max)

  // HERE you can add any setup code needed that is reused across iterations
    Benchmark("Basic",
              configuration: .init(metrics: [.wallClock, .throughput])) { _ in
    }

    Benchmark("Scaled metrics",
              configuration: .init(metrics: BenchmarkMetric.all, scalingFactor: .kilo)) { benchmark in
        for _ in benchmark.scaledIterations {
            blackHole(Int.random(in: benchmark.scaledIterations))
        }
    }

    Benchmark("All metrics",
              configuration: .init(metrics: BenchmarkMetric.all, skip: true)) { _ in
    }
}
```

There is no specific teardown hook, but basically that shared code will be run once and there will only be one benchmark run per process invocation (for precise memory measurements), so basically the process will exit after it has run the benchmark iterations for each of your individual benchmarks - have you had any issues with this approach?

**Comment by ORyanHampton** [comment]
In my testing I found that putting code where you suggest does run once per benchmark running. However, if you have something like a vapor app that you need to startup, or a database that you need to spin-up and tear-down between each benchmark there is some persistence issues. As in, an app or database will setup, but it was not persisting into the benchmarks I was running.

**Comment by ORyanHampton** [comment]
Running setup in that spot also appears to not run how you would expect, that is, any setup there is run, then the benchmarks are run. The flow would look like: Setup -> Benchmarks Registered -> Teardown -> Benchmarks run

**Comment by hassila** [comment]
Thanks for outlining the details, I did a small restructuring of the startup/shutdown hooks and took your changes in the context of https://github.com/ordo-one/package-benchmark/pull/103 (as it will be easier to merge that way as I had a deep PR stack going). Let me know how it works out - and btw, would be great if you could validate the influx output there too, have done some restructuring of all export formats and great with another pair of eyes on that particular output as I don't have influx to test with.

**Pull request closed without merging**
