### PR TITLE
feat: exportable benchmarks

### PR DESCRIPTION
**Pull request by ORyanHampton**
## Description

Added option to gather benchmark data in a JSON file formatted to export into a time series DB.
Saved file structure similar to existing baselines update.

The reason for this feature is to allow for easier collection and storage of benchmarks/performance metrics for time series DB storage and dashboard creation.

## How Has This Been Tested?

I am able to run the export-json cmd and collect the file as expected.

## Minimal checklist:

- [x] I have performed a self-review of my own code 
- [ ] I have added `DocC` code-level documentation for any public interfaces exported by the package
- [ ] I have added unit and/or integration tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hassila** [comment]
Hey @ORyanHampton - many thanks for the PR!

In general I definitely would like to add more export capabilities to benchmark, perhaps it would be worthwhile reworking this slightly in this vein (instead of being specific for just json) - so perhaps just an `export` command which would take an additional type (enum) which to being with could be just 'json-timeseries' (then we could add additional formats more easy going forward). 

`swift package benchmark export json-timeseries`?

As a FYI, we're also actively looking at adding support to HDR histogram data, so we'll in the near future add export capability of all the individual samples and possibly more flexibility of percentiles.

My other concern is possibly the file format (for TS in particular) - the proposed one seems to primarily be a repackaging of the internal serialisation format with a slightly different structure (+ an array of the values) - so far, we've been careful to not commit to the actual internal json representation as a stable format (as we'd like to be able to change it for some more time), so one question would be whether there are any standardised file formats for time series that might be more suitable for long term support?

**Comment by ORyanHampton** [comment]
That makes sense. I added the export option and also implemented an enum flag with one being influx that exports a csv file formatted according to the influxDB standard.

**Comment by hassila** [comment]
> influxDB standard

Super, is it the one documented here? (https://docs.influxdata.com/influxdb/cloud/write-data/developer-tools/csv/) - maybe add a comment with a reference at least (or add to the doc).

Also two of the checks are failing (you need to make the `var exportFormat: ExportFormat` an optional, just trying to run `swift package benchmark` on your branch fails.

Will review properly as soon as the checks pass.

**Review by hassila — APPROVED** [review]

**Comment by hassila** [comment]
Thanks @ORyanHampton for the contribution!

**Comment by hassila** [comment]
https://github.com/ordo-one/package-benchmark/releases/tag/0.5.4

**Comment by hassila** [comment]
@ORyanHampton there was a fairly large refactoring done as part of https://github.com/ordo-one/package-benchmark/commit/b1825fcfbc3887740871b1836107b60e76620320 when multiple export formats were added - it would be great if you could test that the output still matches your expectations (all of the influx stuff is in one file now) - sorry for the inconvenience.

**Comment by hassila** [comment]
(easiest to test is to run from `main`, no proper release have been made yet)

**Pull request merged**
